version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - /home/igor/foodgram-project-react/backend/foodgram/foodgram/.env

  backend:
    depends_on:
      - db
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ../backend/.env

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      
    restart: always
volumes:
  postgres_data:
  static_value:
  media_value: